url: "https://tobizehpanda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tobi Sakatoi" # the name of your site, e.g. ACME Corp.

author:
  name: Tobi Sakatoi
  email: tobizehpanda@gmail.com

photo: /assets/jpg/pfp.jpg

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

feed:
  posts_limit: 3

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  permalink: /:year/:month/:title.html
